blank_issues_enabled: true
contact_links:
  - name: View Available API Versions
    url: https://github.com/beezly/unifi-apis#available-versions
    about: Check which API versions are already available before submitting a request
